WS-70: Card displayed in BrowseSightings page
techswitch-learners/whale-spotting-2022-aug pull request #38
Opened 2022-10-20 14:55 UTC by leong0103

2022-10-20 14:59 UTC, leong0103 commented
![image](https://user-images.githubusercontent.com/110853388/196984891-db2c3529-be5e-46ba-8316-ce362dd641b7.png)

2022-10-25 10:00 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/BrowseSightings.tsx
> +      <h1>Reported Sightings From External Api</h1>
Semantically, there should only be one `<h1>` per page, and that's the whole title of the page. On this page, the `<h1>` would just be "Sightings", and then both of these would be `<h2>`s
```suggestion
      <h1>Sightings</h1>
      <h2>Reported Sightings From External Api</h2>
```

2022-10-25 10:00 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/BrowseSightings.tsx
>        <h1>Reported Sightings</h1>
As above
```suggestion
      <h2>Reported Sightings</h2>
```

2022-10-25 10:03 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/BrowseSightings.tsx
> +      </ul>
This change will massively conflict with another ticket that Nick and Kostas are doing/have done that splits this component into 2, and you'll want to use that here

2022-10-25 10:03 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCardForExternalApi.tsx
> +};
Can you not use the existing `SightingCard.tsx` for this?

2022-10-26 14:13 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/BrowseSightings.tsx
> +  SightingFromExternalApi,
This has been renamed now:
```suggestion
  ExternalSighting,
```

2022-10-26 14:14 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/BrowseSightings.tsx
> +      </ul>
Move this list below the other list, so the "Reported Sightings" comes first

2022-10-26 14:18 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCard.tsx
> +import { Sighting, SightingFromExternalApi } from "../../clients/apiClient";
Again, this was renamed:
```suggestion
import { Sighting, ExternalSighting } from "../../clients/apiClient";
```

2022-10-26 14:19 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCard.tsx
> +    (sighting as SightingFromExternalApi).species.description;
This doesn't make sense, because if it's an External Sighting then the card will say "Number of whales: A blue whale is a big whale!"

2022-10-26 14:19 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCard.tsx
> +    (sighting as SightingFromExternalApi).species.description;
or similar

2022-10-26 14:19 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCard.tsx
> +    (sighting as SightingFromExternalApi).species.description;
You'll need to have some conditions down in the card itself, to display different sections conditionally

2022-10-26 14:20 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCard.tsx
> +    (sighting as SightingFromExternalApi).location.description;
This location description doesn't replace the description of the actual sighting, so should be used in another way

2022-10-26 14:28 UTC, TimLeach635 requested changes

2022-10-26 14:28 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCard.tsx
> +    (sighting as SightingFromExternalApi).species.description;
This can just be
```suggestion
  const whaleCount: number | undefined =
    (sighting as Sighting).whaleCount;
```

2022-10-26 14:28 UTC, TimLeach635 commented on frontend/src/components/browse-sightings-page/SightingCard.tsx
> +    (sighting as SightingFromExternalApi).location.description;
```suggestion
  const description: string | undefined =
    (sighting as Sighting).description;
```

2022-10-26 14:46 UTC, TimLeach635 approved these changes

2022-10-26 14:53 UTC, merged